name: Build and Publish Go Program

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24.2'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build binary
      run: |
        go build -o updates_exporter main.go
      env:
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

    - name: Publish binary
      uses: softprops/action-gh-release@v1
      with:
        files: updates_exporter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

